apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "{{ .Values.kafka.bootstrap }}"
        topics => ["{{ .Values.kafka.log_topic }}"]
        group_id => "{{ .Values.kafka.log_group_id }}"
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:log-level} %{DATA:class}:%{GREEDYDATA:message}" }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-svc:9200"]
        index => "logs-%{+dd.MM.YYYY}"
        retry_on_conflict => 3
        action => "index"
      }
    }