openapi: 3.0.3
info:
  title: Сервис проверки допустимости операций
  version: 1.0.0-SNAPSHOT
servers:
  - url: http://localhost:8888/blocker
paths:
  /operation/check:
    post:
      operationId: CheckClientOperation
      summary: Проверка допустимости операции
      security:
        - bearerAuth: [ ]
      description: Сервис получает информацию об операции и проверяет, возможно ли ее исполнить
      tags:
        - check
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckOperationRq'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResultRs'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponseInfo:
      title: ErrorResponseInfo
      description: Детальная информация об ошибке и ее причинах
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Сообщение о причинах ошибки
    CheckOperationRq:
      title: CheckOperationRq
      description: Запрос на проверку операции
      type: object
      required:
        - requestUser
        - requestService
        - requestAction
      properties:
        requestUser:
          type: string
          description: Пользователь, инициирующий операцию
        requestService:
          type: string
          description: Сервис, от которого поступил запрос
        requestAction:
          type: string
          description: Операция
    CheckResultRs:
      title: CheckResultRs
      description: Результат проверки операции
      type: object
      required:
        - approved
      properties:
        approved:
          type: boolean
          description: true - операция разрешена, false - заблокирована
        reason:
          type: string
          description: Причина блокировки операции