apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: "front-ui"
        metrics_path: '/actuator/prometheus'
        scrape_interval: 15s
        static_configs:
          - targets: ["front-ui-svc:8080"]
            labels:
              app: "front-ui"