apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: bootstrap.kubernetes.io/token
data:
  db-secret.yaml: |
    c3ByaW5nOgogIGRhdGFzb3VyY2U6CiAgICB1c2VybmFtZTogYmFua19hcHBfdXNlcgogICAgcGFzc3dvcmQ6IGNoYW5nZWl0