spring:
  mvc:
    log-request-details: true
  config:
    import: "optional:consul:"
  application:
    name: account-service
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
  datasource:
    url: jdbc:postgresql://bank_db:5432/yandex_practicum
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: bank_account
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master
server:
  port: 8080
keycloak-custom:
  host: keycloack
  port: 8080
logging:
  level:
    org:
      springframework:
        web: DEBUG