openapi: 3.0.3
info:
  title: Сервис работы с уведомлениями
  version: 1.0.0-SNAPSHOT
servers:
  - url: http://localhost:8888/notifications
paths:
  /notification/send:
    post:
      operationId: SendNotification
      summary: Отправить уведомление по операции
      security:
        - bearerAuth: [ ]
      description: Сервис получает запрос на отправку уведомления и выполняет запрос к почтовому серверу
      tags:
        - notification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendNotificationRq'
      responses:
        "200":
          description: "OK"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponseInfo:
      title: ErrorResponseInfo
      description: Детальная информация об ошибке и ее причинах
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Сообщение о причинах ошибки
    SendNotificationRq:
      title: SendNotificationRq
      description: Запрос на отправку уведомления
      type: object
      required:
        - userMail
        - subject
        - text
      properties:
        userMail:
          type: string
          description: почта пользователя
        subject:
          type: string
          description: тема уведомления
        text:
          type: string
          description: текст уведомления