server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service-route
              uri: http://127.0.0.1:8090
              predicates:
                - Path=/accounts/**
              filters:
                - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE