server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service-route
              uri: http://127.0.0.1:8090
              predicates:
                - Path=/accounts/**
              filters:
                - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - id: blocker-service-route
              uri: http://127.0.0.1:8091
              predicates:
                - Path=/blocker/**
              filters:
                - RewritePath=/blocker/?(?<segment>.*), /$\{segment}
            - id: cash-service-route
              uri: http://127.0.0.1:8092
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/cash/?(?<segment>.*), /$\{segment}
            - id: exchange-service-route
              uri: http://127.0.0.1:8093
              predicates:
                - Path=/exchange/**
              filters:
                - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
            - id: notification-service-route
              uri: http://127.0.0.1:8094
              predicates:
                - Path=/notifications/**
              filters:
                - RewritePath=/notifications/?(?<segment>.*), /$\{segment}
            - id: transfer-service-route
              uri: http://127.0.0.1:8095
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/transfer/?(?<segment>.*), /$\{segment}
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE