apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "db.labels" . | nindent 8 }}
spec:
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      {{- include "db.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "db.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Chart.Name }}-data
              mountPath: /var/lib/postgresql/data
            - name: {{ .Chart.Name }}-init
              mountPath: /docker-entrypoint-initdb.d
          {{- with .Values.containerEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envImport }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ .Chart.Name }}-init
          configMap:
            name: {{ .Chart.Name }}-cm
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi