spring:
  config:
    import: "optional:consul:"
  application:
    name: front-ui
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/auth
            token-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/token
            user-info-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/certs
        registration:
          front-ui:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: front-ui
            client-secret: UtEeKuE25MilWrxKqbxzCDoO0Pto8uKe
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile
            clientAuthenticationMethod: client_secret_post
keycloak-custom:
  host: localhost
  port: 9090
rest:
  client:
    accounts:
      url: http://localhost:8090
    cash:
      url: http://localhost:8888/cash
    exchange:
      url: http://localhost:8888/exchange
    transfer:
      url: http://localhost:8888/transfer
management:
  endpoint:
    health:
      probes:
        enabled: true
logging:
  config: classpath:log4j.xml