apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Chart.Name }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master
      mail:
        host: {{ .Values.email.host }}
        port: {{ .Values.email.port }}
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
    notification:
      mail:
        tech-mail-box: {{ .Values.email.box }}
    keycloak-custom:
      host: {{ .Values.identityProvider.host }}
      port: {{ .Values.identityProvider.port }}
    kafka:
      consumer:
        bootstraps: {{ .Values.kafka.bootstrap }}
        topic-name: {{ .Values.kafka.notification_topic }}
        groupId: {{ .Values.kafka.notification_group_id }}
    {{- with .Values.actuatorParams }}
    management:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    logging:
      config: /config/log4j.xml
  log4j.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%C]:%msg%n"/>
            </Console>
            <Kafka name="Kafka" topic="{{ .Values.kafka.log_topic }}">
                <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%C]:%msg%n"/>
                <Property name="bootstrap.servers">{{ .Values.kafka.bootstrap }}</Property>
            </Kafka>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Kafka"/>
            </Root>
            <Logger name="org.apache.kafka" level="INFO" >
                <AppenderRef ref="Console"/>
            </Logger>
        </Loggers>
    </Configuration>