apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: bootstrap.kubernetes.io/token
data:
  mail-secret.yaml: |
    c3ByaW5nOgogIG1haWw6CiAgICB1c2VybmFtZTogdGVzdAogICAgcGFzc3dvcmQ6IHRlc3Q=