apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Chart.Name }}
    kafka:
      producer:
        bootstraps: {{ .Values.kafka.bootstrap }}
        topic-name: {{ .Values.kafka.exchange_topic }}
    {{- with .Values.actuatorParams }}
    management:
      {{- toYaml . | nindent 6 }}
    {{- end }}