spring:
  config:
    import: "optional:consul:"
  application:
    name: transfer-service
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master
      client:
        provider:
          keycloak:
            authorization-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/auth
            token-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/token
            user-info-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/certs
        registration:
          transfer-service:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: transfer-service
            client-secret: 9Wlzt3gzLrsZgBDADrQkHe8eGKwOxzkN
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile
            clientAuthenticationMethod: client_secret_post
keycloak-custom:
  host: keycloack
  port: 8080