apiVersion: v2
name: bank-app
description: Микросервисное приложение "Банк"
type: application
version: 0.1.0
dependencies:
  - name: front-ui
    version: 0.1.0
    repository: "file://charts/front-ui"
  - name: account-service
    version: 0.1.0
    repository: "file://charts/account-service"
  - name: blocker-service
    version: 0.1.0
    repository: "file://charts/blocker-service"
  - name: cash-service
    version: 0.1.0
    repository: "file://charts/cash-service"
  - name: exchange-generator-service
    version: 0.1.0
    repository: "file://charts/exchange-generator-service"
  - name: exchange-service
    version: 0.1.0
    repository: "file://charts/exchange-service"
  - name: notification-service
    version: 0.1.0
    repository: "file://charts/notification-service"
  - name: transfer-service
    version: 0.1.0
    repository: "file://charts/transfer-service"
  - name: postgre-db
    version: 0.1.0
    repository: "file://charts/postgre-db"
  - name: identity-provider
    version: 0.1.0
    repository: "file://charts/identity-provider"
  - name: kafka
    version: 0.1.0
    repository: "file://charts/kafka"
  - name: zipkin
    version: 0.1.0
    repository: "file://charts/zipkin"
  - name: prometheus
    version: 0.1.0
    repository: "file://charts/prometheus"
  - name: grafana
    version: 0.1.0
    repository: "file://charts/grafana"
  - name: logstash
    version: 0.1.0
    repository: "file://charts/logstash"
  - name: elasticsearch
    version: 0.1.0
    repository: "file://charts/elasticsearch"
  - name: kibana
    version: 0.1.0
    repository: "file://charts/kibana"