apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Chart.Name }}
      security:
        oauth2:
          client:
            provider:
              keycloak:
                authorization-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/auth
                token-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/token
                user-info-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/userinfo
                user-name-attribute: sub
                jwk-set-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/certs
            registration:
              front-ui:
                authorizationGrantType: client_credentials
                provider: keycloak
                client-id: front-ui
                client-secret: UtEeKuE25MilWrxKqbxzCDoO0Pto8uKe
                redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
                scope: profile
                clientAuthenticationMethod: client_secret_post
    keycloak-custom:
      host: {{ .Values.identityProvider.host }}
      port: {{ .Values.identityProvider.port }}
    rest:
      client:
        accounts:
          url: http://account-service-svc:8080
        cash:
          url: http://cash-service-svc:8080
        exchange:
          url: http://exchange-service-svc:8080
        transfer:
          url: http://transfer-service-svc:8080
    {{- with .Values.actuatorParams }}
    management:
      {{- toYaml . | nindent 6 }}
    {{- end }}