server:
  port: 8091
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master
keycloak-custom:
  host: localhost
  port: 9090
management:
  endpoint:
    health:
      probes:
        enabled: true