openapi: 3.0.3
info:
  title: Сервис аккаунтов
  version: 1.0.0-SNAPSHOT
servers:
  - url: http://localhost:8888/accounts
paths:
  /user/{username}/info:
    get:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: GetUserInfoByUsername
      security:
        - bearerAuth: []
      summary: Получение информации о пользователе по его имени
      description: Возвращает информацию о пользователе
      tags:
        - user
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoRs'
        "400":
          description: "Некорректный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseInfo'
        "404":
          description: "Пользователь не найден"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseInfo'
  /user/registered/list:
    get:
      operationId: GetAllRegisteredUsers
      summary: Получение информации о зарегистрированных пользователях
      security:
        - bearerAuth: [ ]
      description: Возвращает информацию о пользователях
      tags:
        - user
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredUsersRs'
        "400":
          description: "Некорректный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseInfo'
  /user/register:
    post:
      operationId: RegisterNewUser
      summary: Регистрация нового пользователя в системе
      security:
        - bearerAuth: [ ]
      description: Данные из UI формы передаются в систему и сохраняются в БД
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInfo'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoRs'
        "400":
          description: "Некорректный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseInfo'
  /user/{username}/update:
    put:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: UpdateUserInfo
      summary: Обновить информацию о пользователе
      security:
        - bearerAuth: [ ]
      description: Данные из UI формы передаются в систему и сохраняются в БД
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserInfoRq'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoRs'
  /account/{username}/delete:
    delete:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: DeleteUserAccount
      summary: Удалить счет пользователя
      security:
        - bearerAuth: [ ]
      description: Данные из UI формы передаются в систему и после проверки допустимости действия - счет удаляется из БД
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAccountRq'
      responses:
        "200":
          description: "OK"
  /account/{username}/create:
    post:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: CreateUserAccount
      summary: Создать новый счет пользователя
      security:
        - bearerAuth: [ ]
      description: Данные из UI формы передаются в систему и после проверки допустимости действия - счет создается в БД
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRq'
      responses:
        "200":
          description: "OK"
  /account/{username}/cash:
    put:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: AddCashToAccount
      summary: Внести наличные средства на счет
      security:
        - bearerAuth: [ ]
      description: Данные из UI формы передаются в систему и после проверки допустимости действия - средства зачисляются на счет
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeCashRq'
      responses:
        "200":
          description: "OK"
    get:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: GetCashFromAccount
      summary: Снять наличные средства со счета
      security:
        - bearerAuth: [ ]
      description: Данные из UI формы передаются в систему и после проверки допустимости действия - средства списываются со счета
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeCashRq'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInfo'
        "400":
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInfo'
  /account/{username}/cash/transfer:
    post:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      operationId: TransferCash
      summary: Перевод денег между счетами
      security:
        - bearerAuth: [ ]
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferCashRq'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInfo'
        "400":
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseInfo'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResponseInfo:
      title: ResponseInfo
      description: Базовая информация о результатах вызова
      type: object
      required:
        - status
      properties:
        status:
          type: boolean
          description: успешный или нет вызов
        error:
          type: object
          description: информация об ошибке
          required:
            - errorMessage
          properties:
            errorMessage:
              type: string
              description: текст ошибки
    ErrorResponseInfo:
      title: ErrorResponseInfo
      description: Детальная информация об ошибке и ее причинах
      type: object
      required:
        - responseInfo
      properties:
        responseInfo:
          type: object
          $ref: '#/components/schemas/ResponseInfo'
    UserInfo:
      title: UserInfo
      description: Информация о пользователе
      type: object
      required:
        - id
        - username
        - password
        - fullName
        - birthDay
        - email
        - roles
        - accounts
      properties:
        id:
          type: string
          description: уникальный идентификатор пользователя
        username:
          type: string
          description: уникальное имя пользователя
        password:
          type: string
          description: зашифрованный пароль пользователя
        fullName:
          type: string
          description: полное имя пользователя
        birthDay:
          type: date
          description: точная дата рождения пользователя
        email:
          type: string
          description: почта пользователя
        roles:
          type: array
          items:
            type: string
            description: роль пользователя
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountDetailInfo'
    ShortUserInfo:
      title: ShortUserInfo
      description: Краткая информация о пользователе
      type: object
      required:
        - username
        - fullName
      properties:
        username:
          type: string
          description: уникальное имя пользователя
        fullName:
          type: string
          description: полное имя пользователя
    UserInfoRs:
      title: UserInfoRs
      description: Результаты вызова и информация о пользователе
      required:
        - responseInfo
      properties:
        userInfo:
          type: object
          $ref: '#/components/schemas/UserInfo'
        responseInfo:
          type: object
          $ref: '#/components/schemas/ResponseInfo'
    RegisteredUsersRs:
      title: RegisteredUsersRs
      description: Результаты вызова и информация о зарегистрированных пользователях
      required:
        - responseInfo
      properties:
        users:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/ShortUserInfo'
        responseInfo:
          type: object
          $ref: '#/components/schemas/ResponseInfo'
    UpdateUserInfoRq:
      title: UpdateUserInfoRq
      description: Информация о пользователе к обновлению
      type: object
      properties:
        password:
          type: string
          description: зашифрованный пароль пользователя
        fullName:
          type: string
          description: полное имя пользователя
        birthDay:
          type: date
          description: точная дата рождения пользователя
        email:
          type: string
          description: почта пользователя
    AccountDetailInfo:
      title: AccountDetailInfo
      description: Информация о счете
      type: object
      required:
        - id
        - currency
        - balance
      properties:
        id:
          type: string
          description: id счета
        currency:
          type: string
          description: валюта счета
        balance:
          type: number
          description: количество средств на счете
    UserRegisterInfo:
      title: UserRegisterInfo
      description: Информация о новом пользователе
      type: object
      required:
        - username
        - password
        - fullName
        - birthDay
        - email
        - roles
      properties:
        username:
          type: string
          description: уникальное имя пользователя
        password:
          type: string
          description: зашифрованный пароль пользователя
        fullName:
          type: string
          description: полное имя пользователя
        birthDay:
          type: date
          description: точная дата рождения пользователя
        email:
          type: string
          description: почта пользователя
        roles:
          type: array
          items:
            type: string
            description: роль пользователя

    DeleteAccountRq:
      title: DeleteAccountRq
      description: Запрос на удаление счета пользователя
      type: object
      required:
        - currency
      properties:
        currency:
          type: array
          items:
            type: string
            description: валюта счета
    CreateAccountRq:
      title: CreateAccountRq
      description: Запрос на создание счета пользователя
      type: object
      required:
        - currency
      properties:
        currency:
          type: array
          items:
            type: string
            description: валюта счета
    ChangeCashRq:
      title: ChangeCashRq
      description: Запрос на внесение / снятие наличных средств со счета
      type: object
      required:
        - currency
      properties:
        currency:
          type: string
          description: валюта счета
        value:
          type: number
          description: количество средств
    TransferCashRq:
      title: TransferCashRq
      description: Запрос на перевод денег между счетами пользователей
      type: object
      required:
        - currency
      properties:
        fromAccount:
          type: string
          description: счет, с которого необходимо списать
        fromAccountValue:
          type: number
          description: сумма, которую необходимо списать
        toAccount:
          type: string
          description: счет, на который необходимо зачислить
        toUser:
          type: string
          description: логин пользователя, которому выполняется перевод
        toAccountValue:
          type: number
          description: сумма, которую необходимо зачислить