apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Chart.Name }}
      security:
        oauth2:
          client:
            provider:
              keycloak:
                authorization-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/auth
                token-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/token
                user-info-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/userinfo
                user-name-attribute: sub
                jwk-set-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/certs
            registration:
              front-ui:
                authorizationGrantType: client_credentials
                provider: keycloak
                client-id: front-ui
                redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
                scope: profile
                clientAuthenticationMethod: client_secret_post
    keycloak-custom:
      host: {{ .Values.identityProvider.host }}
      port: {{ .Values.identityProvider.port }}
    rest:
      client:
        accounts:
          url: http://account-service-svc:8080
        cash:
          url: http://cash-service-svc:8080
        exchange:
          url: http://exchange-service-svc:8080
        transfer:
          url: http://transfer-service-svc:8080
    {{- with .Values.actuatorParams }}
    management:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    logging:
      config: /config/log4j.xml
  log4j.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%C]:%msg%n"/>
            </Console>
            <Kafka name="Kafka" topic="{{ .Values.kafka.log_topic }}">
                <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%C]:%msg%n"/>
                <Property name="bootstrap.servers">{{ .Values.kafka.bootstrap }}</Property>
            </Kafka>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Kafka"/>
            </Root>
            <Logger name="org.apache.kafka" level="INFO" >
                <AppenderRef ref="Console"/>
            </Logger>
        </Loggers>
    </Configuration>