spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yandex_practicum
    username: bank_app_user
    password: changeit
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: bank_account