openapi: 3.0.3
info:
  title: Сервис работы с наличными средствами
  version: 1.0.0-SNAPSHOT
servers:
  - url: http://localhost:8091
  - url: http://cash-service:8080
paths:
  /cash/update:
    post:
      operationId: UpdateCash
      summary: Внести или снять наличные средства со счета
      description: Сервис получает запрос на зачисление или снятие средств. Выполняется обращение к account-service, blocker-service, notification-service
      tags:
        - cash
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeCashRq'
      responses:
        "200":
          description: "OK"
components:
  schemas:
    ErrorResponseInfo:
      title: ErrorResponseInfo
      description: Детальная информация об ошибке и ее причинах
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Сообщение о причинах ошибки
    ChangeCashRq:
      title: ChangeCashRq
      description: Запрос на внесение / снятие наличных средств со счета
      type: object
      required:
        - action
        - userName
        - currency
        - value
      properties:
        action:
          type: string
          description: желаемое действие - внести или снять
        userName:
          type: string
          description: логин пользователя
        currency:
          type: string
          description: валюта счета
        value:
          type: number
          description: количество средств