spring:
  codec:
    log-request-details: true
  config:
    import: "optional:consul:"
  application:
    name: front-ui
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/auth
            token-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/token
            user-info-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master/protocol/openid-connect/certs
        registration:
          front-ui:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: front-ui
            client-secret: UtEeKuE25MilWrxKqbxzCDoO0Pto8uKe
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile
            clientAuthenticationMethod: client_secret_post
logging:
  level:
    org:
      springframework:
        web: TRACE
  org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
keycloak-custom:
  host: keycloack
  port: 8080