replicaCount: 1
image:
  repository: exchange-generator-service
  pullPolicy: Never
  tag: "latest"
containerEnv:
  - name: SPRING_CONFIG_LOCATION
    value: /config/application.yaml
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 360
  periodSeconds: 20
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 120
  periodSeconds: 20
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3
volumes:
  - name: application-configuration
    configMap:
      name: exchange-generator-service-config
volumeMounts:
  - name: application-configuration
    mountPath: /config
    readOnly: true
nodeSelector: {}
tolerations: []
affinity: {}
actuatorParams:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin-svc:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
kafka:
  bootstrap: kafka-svc:9092
  exchange_topic: "CURRENCY.ACTUAL"