openapi: 3.0.3
info:
  title: Сервис работы с курсами валют
  version: 1.0.0-SNAPSHOT
servers:
  - url: http://localhost:8888/exchange
paths:
  /currency/info/actual:
    get:
      operationId: ActualCurrencyInfo
      summary: Получить актуальную информацию о курсах валют
      security:
        - bearerAuth: [ ]
      description: Сервис возвращает актуальную информацию по текущему курсу валют
      tags:
        - currency
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyInfoRs'
  /currency/info/update:
    put:
      operationId: UpdateCurrencyInfo
      summary: Обновить информацию по курсам валют
      security:
        - bearerAuth: [ ]
      description: Сервис получает запрос с информацией о новом курсе валют и сохраняет его у себя в памяти
      tags:
        - currency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCurrencyRq'
      responses:
        "200":
          description: "OK"
  /currency/exchange:
    post:
      operationId: ExchangeCurrency
      summary: Перевод валют по текущему курсу
      security:
        - bearerAuth: [ ]
      tags:
        - currency
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeCurrencyRq'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeCurrencyRs'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResponseInfo:
      title: ResponseInfo
      description: Базовая информация о результатах вызова
      type: object
      required:
        - status
      properties:
        status:
          type: boolean
          description: успешный или нет вызов
        error:
          type: object
          description: информация об ошибке
          required:
            - errorMessage
          properties:
            errorMessage:
              type: string
              description: текст ошибки
    CurrencyInfo:
      title: CurrencyInfo
      description: Информация о курсе валюты
      type: object
      required:
        - name
        - shortName
        - value
      properties:
        name:
          type: string
          description: международное название валюты
        shortName:
          type: string
          description: сокращенное название валюты
        value:
          type: number
          description: текущий курс валюты (в рублях)
    CurrencyInfoRs:
      title: CurrencyInfoRs
      description: Результаты вызова и информация о курсах валют
      required:
        - responseInfo
      properties:
        currencyInfo:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/CurrencyInfo'
        responseInfo:
          type: object
          $ref: '#/components/schemas/ResponseInfo'
    UpdateCurrencyRq:
      title: UpdateCurrencyRq
      description: Запрос на обновление информации о курсах валют
      required:
        - CurrencyInfo
      properties:
        currencyInfo:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/CurrencyInfo'
    ExchangeCurrencyRq:
      title: ExchangeCurrencyRq
      description: Запрос на перевод валют по текущему курсу
      required:
        - fromCurrency
        - toCurrency
        - fromValue
      properties:
        fromCurrency:
          type: string
          description: текущая валюта
        toCurrency:
          type: string
          description: целевая валюта
        fromValue:
          type: number
          description: сумма в текущей валюте
    ExchangeCurrencyRs:
      title: ExchangeCurrencyRs
      description: Результат перевода валют по текущему курсу
      required:
        - exchangedCurrency
        - exchangedValue
      properties:
        exchangedCurrency:
          type: string
          description: валюта
        exchangedValue:
          type: number
          description: сумма