apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Chart.Name }}
      datasource:
        url: {{ .Values.db.url }}
        driver-class-name: {{ .Values.db.driver }}
      jpa:
        properties:
          hibernate:
            default_schema: {{ .Values.db.schema }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master
    keycloak-custom:
      host: {{ .Values.identityProvider.host }}
      port: {{ .Values.identityProvider.port }}
    {{- with .Values.actuatorParams }}
    management:
      {{- toYaml . | nindent 6 }}
    {{- end }}