replicaCount: 1
image:
  repository: openzipkin/zipkin-slim
  pullPolicy: IfNotPresent
  tag: "latest"
command: ['start-zipkin']
containerArgs: []
containerEnv:
  - name: SELF_TRACING_ENABLED
    value: "true"
  - name: STORAGE_TYPE
    value: "mem"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 9411
resources: {}
volumes: {}
volumeMounts: {}
nodeSelector: {}
tolerations: []
affinity: {}
readinessProbe:
  httpGet:
    path: /health
    port: 9411
  initialDelaySeconds: 120
  periodSeconds: 20
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3