replicaCount: 1
image:
  repository: docker.elastic.co/logstash/logstash
  pullPolicy: IfNotPresent
  tag: "9.0.0"
command: []
containerArgs: []
containerEnv: []
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5044
resources: {}
volumes:
  - name: pipeline-volume
    configMap:
      name: logstash-config
volumeMounts:
  - name: pipeline-volume
    mountPath: /usr/share/logstash/pipeline
    readOnly: true
nodeSelector: {}
tolerations: []
affinity: {}
kafka:
  bootstrap: kafka-svc:9092
  log_topic: "BANK.APP.LOGGING"
  log_group_id: logstash